customhost = "employee.cceox3i7xlby.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leesiaoyu-employee"
customregion = "us-east-1"